name: create-api-in-apim
on: 
 push:
   paths-ignore:
     - '**/create-api-in-apim.yaml'
     - '**/*.txt'
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all}}
      ts: ${{ steps.changes.outputs.ts }}
    steps:
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: checkout
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name : read swagger json
        if: ${{ steps.checkout.outputs.added != '' }}
        id: readspec
        run: |
          swagger=`cat ./${{ steps.checkout.outputs.added}}`
          swagger="${swagger//'%'/'%25'}"
          swagger="${swagger//$'\n'/'%0A'}"
          content="${swagger//$'\r'/'%0D'}"
          echo "::set-output name=swaggerJson::$swagger"
      - if: ${{ steps.checkout.outputs.added != '' }}
        run: |
          echo "${{fromJson(steps.readspec.outputs.swaggerJson).info.title}}"  
      - name: create api in apim
        if: ${{ steps.checkout.outputs.added != '' }}
        id: createapi
        run : |
          echo "${{steps.readswagger.outputs.content}}"
          output=$(curl -k -H "Authorization: Bearer 646a0f14-07d7-3c5d-9476-ab68b047fda1" -F file=@${{ steps.checkout.outputs.added }} -F additionalProperties="{\"name\":\"${{fromJson(steps.readspec.outputs.swaggerJson).info.title}}\",\"version\":\"${{fromJson(steps.readspec.outputs.swaggerJson).info.version}}\",\"context\":\"/${{fromJson(steps.readspec.outputs.swaggerJson).info.title}}\"}" "http://7dce17f515bf.ngrok.io/api/am/publisher/v1/apis/import-openapi")
          echo "::set-output name=responseJson::$output"
      -  if: ${{ steps.checkout.outputs.added != '' }}
         run : |
          echo "${{fromJson(steps.createapi.outputs.responseJson).id}}"
          git config --local user.name ${{ github.actor }}
          echo "${{ steps.checkout.outputs.added }}::${{fromJson(steps.createapi.outputs.responseJson).id}}" >> id.txt
          git add id.txt
          git commit -m "Add changes"
      - name: Push id.txt file changes 
        if: ${{ steps.checkout.outputs.added != '' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
      - name: read id.txt for api update
        if: ${{ steps.checkout.outputs.modified != '' }}
        id: idfile
        uses: juliangruber/read-file-action@v1
        with:
          path: ./id.txt
      - name: get api id from id.txt file
        if: ${{ steps.checkout.outputs.modified != '' }}
        uses: rishabhgupta/split-by@v1
        id: split
        with:
          string: echo ${{ steps.idfile.outputs.content }} 
          split-by: '::'
      - name: update api in apim
        if: ${{ steps.checkout.outputs.modified != '' }}
        run : |
          echo ${{ steps.split.outputs._1}}
          update=$(curl -k -X PUT -H "Authorization: Bearer 646a0f14-07d7-3c5d-9476-ab68b047fda1" -F apiDefinition=@${{ steps.checkout.outputs.modified }} "http://7dce17f515bf.ngrok.io/api/am/publisher/v1/apis/${{ steps.split.outputs._1 }}/swagger")
