name: publish-in-apim
on: 
 push:
   paths-ignore:
     - '**/publish-in-apim.yaml'
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      ts: ${{ steps.changes.outputs.ts }}
    steps:
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: checkout
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.checkout.outputs.all }}"
          echo "Added:"
          echo "${{ steps.checkout.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.checkout.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.checkout.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.checkout.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.checkout.outputs.added_modified }}"
      - name: get content of modifiled file
        id: getYaml
        run: echo "::set-output name=yaml::$(cat ${{ steps.checkout.outputs.modified }})"
      - name: curl
        id: curl
        run : |
          curl -k -H "Authorization: Bearer b576211b-2479-30f9-abd8-f3ef5992703d" -F file=@${{ steps.checkout.outputs.modified }} -F additionalProperties="{\"name\":\"sanuli\",\"version\":\"1.2.3\",\"context\":\"/sanuli\",\"endpointConfig\":{\"endpoint_type\":\"http\",\"sandbox_endpoints\":{\"url\":\"https://localhost:9443/am/sample/pizzashack/v1/api/\"},\"production_endpoints\":{\"url\":\"https://localhost:9443/am/sample/pizzashack/v1/api/\"}}}" "http://adf3f17ae214.ngrok.io/api/am/publisher/v1/apis/import-openapi"
      - name: create a text file
        run: |
          echo "::set-output name=id.txt::$(cat ${{ steps.curl.outputs.response  }})"
      - name: Commit files 
        run: |
          git config --local user.name ${{ github.actor }}
          git add id.txt
          git commit -m "Add changes"
      - name: Push changes 
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
