name: publish-in-apim
on: 
 push:
   paths-ignore:
     - '**/publish-in-apim.yaml'
     - '**/*.txt'
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      ts: ${{ steps.changes.outputs.ts }}
    steps:
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: checkout
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.checkout.outputs.all }}"
          echo "Added:"
          echo "${{ steps.checkout.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.checkout.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.checkout.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.checkout.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.checkout.outputs.added_modified }}"
          echo "if condition"
          echo ${{ steps.checkout.outputs.added != '' }}
      - name: createapi
        if: ${{ steps.checkout.outputs.added != '' }}
        id: createapi
        run : |
          output=$(curl -k -H "Authorization: Bearer dc658218-b996-3e2b-999e-f44cf590cd9c" -F file=@${{ steps.checkout.outputs.added }} -F additionalProperties="{\"name\":\"sanuli\",\"version\":\"1.2.3\",\"context\":\"/sanuli\",\"endpointConfig\":{\"endpoint_type\":\"http\",\"sandbox_endpoints\":{\"url\":\"https://localhost:9443/am/sample/pizzashack/v1/api/\"},\"production_endpoints\":{\"url\":\"https://localhost:9443/am/sample/pizzashack/v1/api/\"}}}" "http://edba63783ff9.ngrok.io/api/am/publisher/v1/apis/import-openapi")
          echo "::set-output name=responseJson::$output"
      -  if: ${{ steps.checkout.outputs.added != '' }}
         run : |
          echo "${{fromJson(steps.createapi.outputs.responseJson).id}}"
          git config --local user.name ${{ github.actor }}
          echo "${{ steps.checkout.outputs.added }} ${{fromJson(steps.createapi.outputs.responseJson).id}}" >> id.txt
          git add id.txt
          git commit -m "Add changes"
      - name: Push changes 
        if: ${{ steps.checkout.outputs.added != '' }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
      - name: updateapi
        if: ${{ steps.checkout.outputs.modified != '' }}
        id: updateapi
        run : |
          update=$(curl -k -X PUT -H "Authorization: Bearer dc658218-b996-3e2b-999e-f44cf590cd9c" -F apiDefinition=@${{ steps.checkout.outputs.modified }} "http://edba63783ff9.ngrok.io/api/am/publisher/v1/apis/0d6a38c2-3d16-4d45-bab6-45ce6c491cb0/swagger")
