name: publish-in-apim
on: push
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      ts: ${{ steps.changes.outputs.ts }}
    steps:
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: checkout
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        run: |
          echo "All:"
          echo "${{ steps.checkout.outputs.all }}"
          echo "Added:"
          echo "${{ steps.checkout.outputs.added }}"
          echo "Removed:"
          echo "${{ steps.checkout.outputs.removed }}"
          echo "Renamed:"
          echo "${{ steps.checkout.outputs.renamed }}"
          echo "Modified:"
          echo "${{ steps.checkout.outputs.modified }}"
          echo "Added+Modified:"
          echo "${{ steps.checkout.outputs.added_modified }}"
      - name: get content of modifiled file
        id: getYaml
        run: echo "::set-output name=yaml::$(cat ${{ steps.checkout.outputs.modified }})"
      - name: curl
        uses: wei/curl@master
        with:
          args: http://264dbc7fa5e5.ngrok.io/banksvc/current
